name: "Increment the version code of your project"
description: "This action will increment the version code directly in build.gradle"
inputs:
  gradlePath:
    description: "Gradle path to override version"
    required: true
    default: "app/build.gradle"
  versionCode:
    description: "The new version code"
    required: false
  versionName:
    description: "The new version name"
    required: false
  versionCodeSuffix:
    description: "The version code suffix"
    required: false
  versionNameSuffix:
    description: "The version name suffix"
    required: false
outputs:
  result: # id of output
    description: "Action Result"
runs:
  using: "node12"
  main: "index.js"
branding:
  color: 'black'
  icon: 'box'
